title: "Annie's and David's Project Data"
author: "Anne Kelly"
date: "10/17/2021"
output: html_document
---
```{r}
library(tidyverse)
```

```{r}
library(readr)
Womanfertility <- read_csv("Womanfertility.csv")
View(Womanfertility)
Woman.long <- pivot_longer(Womanfertility, cols=!country, names_to = "Year",values_to="Fertility")
Woman.long$Year <- as.numeric(Woman.long$Year)
Woman.long<-na.omit(Woman.long)
Woman.US <- subset(Woman.long, Woman.long$country=="United States")
ggplot(Woman.long, aes(x =Year, y=Fertility, group=country))+ #geom_smooth() + 
  geom_line(color="gray80") +
  geom_line(data=Woman.US, mapping=aes(x=Year, y=Fertility), color="blue") + 
  theme(legend.position = "none") +theme_minimal() + ggtitle("U.S. Woman Fertility")
plot.circ <- function(cutoff){
Woman.US$fertility.above <- ifelse(Woman.US$fertility > cutoff, 
                                    Woman.US$fertility, NA)
data <- cbind(1:5); 
data1 <- cbind(15:20)
data2 <- cbind(25:30)
}
x <- c(2,5,3,9,8,11,6)
count <- 0
for (val in x) {
if(val %% 2 == 0)  count = count+1
}
print(count)
for (i in 1:nrow(Woman.US)) {
  if (i == 1) {
    print("i is 1")
  } else {
    print("i is not 1")
  }
  for (j in 1:nrow(Woman.US)) {
    print(paste("FOR 2: ", j))
    for (k in 1:nrow(Woman.US)) {
      cat(paste("FOR 3: ", k, "\n"))
    }
  }
}
```
